
# This is a basic workflow to help you get started with Actions

name: Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
          
      - name: Try to build Web
        run: dotnet build Tandro.Dev.Forums.Web/Tandro.Dev.Forums.Web.csproj
        
      - name: Try to build Core
        run: dotnet build Tandro.Dev.Forums.Core/Tandro.Dev.Forums.Core.csproj
